# -*- mode: sh -*-

export CLICOLOR=1

if [[ -f "$HOME/.bash_localrc" ]]; then
    . "$HOME"/.bash_localrc
fi

. "$HOME/.bash_aliases"
. "$HOME/.bash_prompt"
. "$HOME/.bash_functions"

export LSCOLORS=exfxcxdxbxegedabagacad

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
if [[ -d $BASHGPT/bin/Release ]]; then
    export PATH=$PATH:$BASHGPT/bin/Release
fi

# pip is screwed up?
export PYTHONPATH=/opt/homebrew/lib/python3.9/site-packages

export PATH="$PATH:$(go env GOPATH)/bin"
export GOPHERJS_GOROOT="$(go env GOROOT)"
export SUBLIST3R_PY=/Users/jeff/Projects/Sublist3r/sublist3r.py

eval "$(/opt/homebrew/bin/brew shellenv)"

HISTFILESIZE=10000000
HISTSIZE=10000000

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/apps/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/apps/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/apps/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/apps/google-cloud-sdk/completion.zsh.inc"; fi

if [ -d "$HOME/.cargo/bin" ]; then
  export PATH=$PATH:$HOME/.cargo/bin
fi
