# -*- mode: sh -*-

alias cd..='cd ..'
alias l='ls'
alias ll='ls -l'
alias la='ls -a'
alias m='more'
alias ips='nmap -sP 192.168.1.*'
alias gitpush='git push -u origin master'
alias formatjson='python -m json.tool'
alias http_server='python -m http.server'
alias goutil_install_local='pushd ~/Projects/spudtrooper/goutil; ./scripts/install_local.sh; popd'
alias sublist3r='python ~/Projects/github/Sublist3r/sublist3r.py'
alias sublister='python ~/Projects/github/Sublist3r/sublist3r.py'
alias restart_mongodb='sudo brew services restart mongodb-community'
alias mynmap='nmap -A --osscan-guess -T4 -v -sV'
alias myarp-scan='arp-scan --localnet | sort'
alias nq='networkQuality'
alias python='python3'
alias pip='pip3'

alias tf='terraform'
alias tfw='terraform workspace'
alias tfws='terraform workspace select'
alias tfs='terraform state'

alias tshark='/Applications/Wireshark.app/Contents/MacOS/tshark'

alias b='bashgpt'
alias chrome_incognito='open -na "Google Chrome" --args -incognito duckduckgo.com'

alias paths='echo $PATH | tr ":" "\n"'
alias flush_dns_cache='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
alias stealthcurl="node ~/Projects/spudtrooper/stealthcurl/index.js"
alias gh_repo_create='gh repo create --clone --public'
alias abspath='readlink -f'
alias trim="sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'"
alias newproj='~/Projects/jeffpalm/newproj/scripts/run.sh'
alias dotfiles_install='pushd ~/Projects/spudtrooper/dotfiles; ./scripts/install.sh; popd'
alias dotfiles_install_and_commit='pushd ~/Projects/spudtrooper/dotfiles; ./scripts/install.sh; ./scripts/commit.sh; popd'
alias gm='glow -p'

