# -*- mode: sh -*-

export CLICOLOR=1

. "$HOME/.bash_aliases"
. "$HOME/.bash_prompt"
. "$HOME/.bash_functions"

if [[ -f "$HOME/.bash_localrc" ]]; then
  . "$HOME"/.bash_localrc
fi

export LSCOLORS=exfxcxdxbxegedabagacad

export ANDROID_HOME=$HOME/Library/Android/sdk
if [[ -d "$ANDROID_HOME/" ]]; then
  export PATH=$PATH:$ANDROID_HOME/emulator
  export PATH=$PATH:$ANDROID_HOME/tools
  export PATH=$PATH:$ANDROID_HOME/tools/bin
  export PATH=$PATH:$ANDROID_HOME/platform-tools
fi
if [[ -d $BASHGPT/bin/Release ]]; then
  export PATH=$PATH:$BASHGPT/bin/Release
fi
if [[ -d "/opt/homebrew/opt/ruby/bin" ]]; then
  export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
fi
if [[ -d "$HOME/.rubies/ruby-master/bin" ]]; then
  export PATH=$HOME/.rubies/ruby-master/bin:$PATH
fi
if [[ -d "$HOME/.bun/bin" ]]; then
  export PATH=$HOME/.bun/bin:$PATH
fi
if [[ -d "/Applications/google-cloud-sdk/bin" ]]; then
  export PATH=/Applications/google-cloud-sdk/bin:$PATH
fi

eval "$(/opt/homebrew/bin/brew shellenv)"

if [ -d "$HOME/go/bin" ]; then
  export PATH=$PATH:$HOME/go/bin
fi
export PATH="$PATH:$(go env GOPATH)/bin"
export GOPHERJS_GOROOT="$(go env GOROOT)"
export SUBLIST3R_PY=$HOME/Projects/Sublist3r/sublist3r.py

export HISTFILESIZE=10000000
export HISTSIZE=10000000

if [ -d "$HOME/.cargo/bin" ]; then
  export PATH=$PATH:$HOME/.cargo/bin
fi

if [[ -d "/opt/homebrew/opt/postgresql@16/bin" ]]; then
  export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"
fi

echo 'export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"' >>~/.zshrc

# Creates an alias for every file in ~/.bash_functions.d with extension .sh using the
# file name without extension as the alias name.
for f in ~/.bash_functions.d/*.sh; do
  if [[ -d $f ]]; then
    continue
  fi
  alias_name="$(basename "$f")"
  alias_name="${alias_name%.*}"
  alias $alias_name="$f"
  alias_name_with_hypens="${alias_name//_/-}"
  alias $alias_name_with_hypens="$f"
  alias_name_with_underscores="${alias_name//-/_}"
  alias $alias_name_with_underscores="$f"
  alias_name_no_spaces="${alias_name/ //}"
  alias $alias_name_no_spaces="$f"
done

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Applications/google-cloud-sdk/path.zsh.inc' ]; then . '/Applications/google-cloud-sdk/path.zsh.inc'; fi

export PYTHON_HOME=$HOME/Library/Python/3.12
export PATH=$PYTHON_HOME/bin:$PATH

if [[ -d "$HOME/anaconda3/bin" ]]; then
  export PATH="$HOME/anaconda3/bin:$PATH"
fi
